### ISSUE TITLE
Make it possible to get the next page of subscribers of a group using our SDK

### ISSUE THREAD

**Issue by dwbrasil0** [mailerlite/mailerlite-php#13]
**Original conversation:** https://themailergroup.slack.com/archives/C03GPTBQKUK/p1691663547247109

Currently, our `getSubscribers` method doesn’t have any page or cursor information, it's missing second parameter $params, where ‘cursor’ could be passed
https://github.com/mailerlite/mailerlite-php/blob/1b86b05e1f5557fead35a1a3b4ad739e94d0933f/src/Endpoints/Group.php#L70

**Comment by johnkelesidis** [comment]
Pr is here: https://github.com/mailerlite/mailerlite-php/pull/14

@npetrunova  Leaving pr description here since the sdk is on a public repo

Description
Adds support for query params in the group subscriber get call

Risks
None

**Comment by johnkelesidis** [comment]
released
