### ISSUE TITLE
Requires PHP8.1, not 7.4

### ISSUE THREAD

**Issue by ashwebstudio** [mailerlite/mailerlite-php#9]
- [ ] Search for existing issues

### Summary

When using this SDK, I get the following error:

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.22

Requiring 8.1 is not yet feasible in my attempts to use this in a WordPress plugin which only has PHP 7.4 as its minimum requirement.

### Expected Results

I should be able to use this on PHP 7.4 and greater according to the documentation

### Actual Results

You need PHP 8.1. The error does go away when I use at minimum 8.1.

### Steps to Reproduce

Make any request and this is the result I get.

**Comment by nklmilojevic** [comment]
Hi, 

You seem to have packages locally that need PHP 8.1. We have tested our SDK and it works on 8.0 (that you are running).

**Comment by ashwebstudio** [comment]
This is the only package I am requesting via Composer and it tells me it needs 8.1. Even 8.0 is not enough, I need it working on 7.4 as the documentation says it does.


 <https://www.ashwebstudio.com/>	Derek Ashauer
www.ashwebstudio.com <https://www.ashwebstudio.com/>
Ph / 970.541.9087

**Comment by nklmilojevic** [comment]
We have recently verified that the following versions are compatible:

* 7.4
* 8.0
* 8.1

Kindly take a moment to double-check your configuration, as it seems there might be a discrepancy in your local setup. 
Additionally, please note that your message indicates you're running PHP 8.0 locally, not 7.4.

**Comment by ashwebstudio** [comment]
I understand at that moment I was on PHP 8.0. I test on all kinds of versions of PHP. I am making a WordPress plugin and it needs to at least support 7.4. The errors I am getting prevent the SDK from being used and say PHP 8.1 is required. My entire composer file only asks for the MailerLite PHP SDK, no other requirements and yet it insists that PHP 8.1 is required.


 <https://www.ashwebstudio.com/>	Derek Ashauer
www.ashwebstudio.com <https://www.ashwebstudio.com/>
Ph / 970.541.9087

**Comment by MikeTV** [comment]
Turns out if you run composer under PHP 8.0+, it'll mark dependencies as requiring >= 8.1.0 (in `platform_check.php`).  Running composer under PHP 7.4 solved the issue.
